import React, { useState } from 'react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import Papa from 'papaparse';
import API from '../api';
import EmailComposer from './EmailComposer';

export default function ReportGenerator({ 
  feedback, 
  subjects, 
  user, 
  reportType = 'teacher',
  title = 'Feedback Report',
  dateRange = { start: '', end: '' }
}) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [emailing, setEmailing] = useState(false);
  const [selectedTeacher, setSelectedTeacher] = useState('');
  const [selectedSubject, setSelectedSubject] = useState('');
  const [internalDateRange, setInternalDateRange] = useState(dateRange);
  const [showEmailComposer, setShowEmailComposer] = useState(false);
  const [emailStatus, setEmailStatus] = useState('');

  const getFilteredData = () => {
   let filteredFeedback = feedback ? [...feedback] : [];
    
    if (dateRange.start) {
      filteredFeedback = filteredFeedback.filter(f => 
        new Date(f.created_at) >= new Date(dateRange.start)
      );
    }
    
    if (dateRange.end) {
      const endDate = new Date(dateRange.end);
      endDate.setHours(23, 59, 59, 999);
      filteredFeedback = filteredFeedback.filter(f => 
        new Date(f.created_at) <= endDate
      );
    }
    
    return filteredFeedback;
  };

  const sendEmailReport = async () => {
    setShowEmailComposer(true);
  };

  const handleEmailSent = (result) => {
    setEmailStatus(`Email sent successfully to ${result.teacher_name}`);
    setTimeout(() => setEmailStatus(''), 5000);
  };

  const generateCSV = () => {
    setIsGenerating(true);
    
    try {
      const filteredData = getFilteredData();
      
      const csvData = filteredData.map(item => ({
        'Subject': item.subject_name || 'Unknown',
        'Student': item.student_name || 'Unknown',
        'Rating': item.rating,
        'Comment': item.comment || '',
        'Date': new Date(item.created_at).toLocaleDateString(),
        'Time': new Date(item.created_at).toLocaleTimeString()
      }));

      const csv = Papa.unparse(csvData);
      const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      const url = URL.createObjectURL(blob);
      
      link.setAttribute('href', url);
      link.setAttribute('download', `${title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error generating CSV:', error);
      alert('Failed to generate CSV. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const generatePDF = () => {
    console.log('Starting PDF generation...');
    setIsGenerating(true);
    const filteredData = getFilteredData();
    console.log('Filtered data:', filteredData);
    
    try {
      const doc = new jsPDF();
      console.log('jsPDF instance created:', doc);
      
      // Add title
      doc.setFontSize(20);
      doc.text(title, 14, 20);
      console.log('Title added');
      
      // Add metadata
      doc.setFontSize(12);
      doc.text(`Generated by: ${user?.first_name || user?.email} (${user?.role})`, 14, 30);
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 37);
      
      if (dateRange.start || dateRange.end) {
        doc.text(`Date Range: ${dateRange.start || 'All'} to ${dateRange.end || 'Present'}`, 14, 44);
      }
      
      doc.text(`Total Feedback: ${filteredData.length}`, 14, 51);
      
      // Add statistics
      if (filteredData.length > 0) {
        const avgRating = (filteredData.reduce((sum, f) => sum + (f.rating || 0), 0) / filteredData.length).toFixed(1);
        const ratingCounts = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
        filteredData.forEach(f => ratingCounts[f.rating]++);
        
        doc.text(`Average Rating: ${avgRating}`, 14, 58);
        
        // Rating distribution
        doc.setFontSize(10);
        let yPos = 68;
        doc.text('Rating Distribution:', 14, yPos);
        Object.entries(ratingCounts).forEach(([rating, count]) => {
          yPos += 6;
          const percentage = ((count / filteredData.length) * 100).toFixed(1);
          doc.text(`${rating} Star: ${count} (${percentage}%)`, 20, yPos);
        });
      }
      
      // Add feedback table
      const tableData = filteredData.map(item => [
        item.subject_name || 'Unknown',
        item.student_name || 'Unknown',
        item.rating.toString(),
        new Date(item.created_at).toLocaleDateString(),
        item.comment ? item.comment.substring(0, 50) + (item.comment.length > 50 ? '...' : '') : ''
      ]);
      
      console.log('Table data prepared:', tableData);
      
      // Check if autoTable is available
      if (doc.autoTable) {
        console.log('Using autoTable');
        doc.autoTable({
          head: [['Subject', 'Student', 'Rating', 'Date', 'Comment']],
          body: tableData,
          startY: filteredData.length > 0 ? 95 : 65,
          styles: { fontSize: 9 },
          headStyles: { fillColor: [59, 130, 246] },
          alternateRowStyles: { fillColor: [245, 245, 245] }
        });
      } else {
        console.log('autoTable not available, using manual table');
        // Fallback: manual table creation
        let yPos = filteredData.length > 0 ? 95 : 65;
        doc.setFontSize(10);
        
        // Headers
        doc.text('Subject', 14, yPos);
        doc.text('Student', 60, yPos);
        doc.text('Rating', 110, yPos);
        doc.text('Date', 140, yPos);
        doc.text('Comment', 170, yPos);
        
        yPos += 10;
        
        // Data rows
        tableData.forEach(row => {
          doc.text(row[0], 14, yPos);
          doc.text(row[1], 60, yPos);
          doc.text(row[2], 110, yPos);
          doc.text(row[3], 140, yPos);
          doc.text(row[4], 170, yPos);
          yPos += 8;
        });
      }
      
      // Save the PDF
      console.log('Saving PDF...');
      doc.save(`${title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
      console.log('PDF saved successfully');
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const generateSummaryPDF = () => {
    setIsGenerating(true);
    const filteredData = getFilteredData();
    
    try {
      const doc = new jsPDF();
      
      // Title
      doc.setFontSize(20);
      doc.text(`${title} - Summary`, 14, 20);
      
      // Metadata
      doc.setFontSize(12);
      doc.text(`Generated by: ${user?.first_name || user?.email} (${user?.role})`, 14, 30);
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 37);
      
      if (dateRange.start || dateRange.end) {
        doc.text(`Date Range: ${dateRange.start || 'All'} to ${dateRange.end || 'Present'}`, 14, 44);
      }
      
      // Overall Statistics
      doc.setFontSize(14);
      doc.text('Overall Statistics', 14, 55);
      doc.setFontSize(12);
      
      if (filteredData.length > 0) {
        const avgRating = (filteredData.reduce((sum, f) => sum + (f.rating || 0), 0) / filteredData.length).toFixed(1);
        const ratingCounts = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
        filteredData.forEach(f => ratingCounts[f.rating]++);
        
        doc.text(`Total Feedback: ${filteredData.length}`, 14, 65);
        doc.text(`Average Rating: ${avgRating} / 5.0`, 14, 72);
        
        // Rating distribution chart (text-based)
        doc.setFontSize(14);
        doc.text('Rating Distribution', 14, 85);
        doc.setFontSize(12);
        
        let yPos = 95;
        const maxCount = Math.max(...Object.values(ratingCounts));
        Object.entries(ratingCounts).forEach(([rating, count]) => {
          const percentage = ((count / filteredData.length) * 100).toFixed(1);
          const barLength = maxCount > 0 ? (count / maxCount) * 50 : 0;
          
          doc.text(`${rating} Star:`, 14, yPos);
          doc.rect(45, yPos - 3, barLength, 5, 'F');
          doc.text(`${count} (${percentage}%)`, 100, yPos);
          yPos += 8;
        });
        
        // Subject-wise breakdown
        if (reportType === 'hod') {
          const subjectStats = {};
          filteredData.forEach(f => {
            const subject = f.subject_name || 'Unknown';
            if (!subjectStats[subject]) {
              subjectStats[subject] = { count: 0, totalRating: 0 };
            }
            subjectStats[subject].count++;
            subjectStats[subject].totalRating += f.rating;
          });
          
          doc.setFontSize(14);
          doc.text('Subject Performance', 14, yPos + 10);
          doc.setFontSize(12);
          yPos += 20;
          
          Object.entries(subjectStats).forEach(([subject, stats]) => {
            const avgRating = (stats.totalRating / stats.count).toFixed(1);
            doc.text(`${subject}:`, 14, yPos);
            doc.text(`${stats.count} feedback, Avg: ${avgRating}`, 60, yPos);
            yPos += 8;
          });
        }
      } else {
        doc.text('No feedback data available for the selected criteria.', 14, 65);
      }
      
      // Save the PDF
      doc.save(`${title.replace(/\s+/g, '_')}_Summary_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      console.error('Error generating summary PDF:', error);
      alert('Failed to generate summary PDF. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="bg-white p-6 rounded-lg shadow">
      <h3 className="text-lg font-semibold mb-4">Generate Reports</h3>
      
      {emailStatus && (
        <div className="mb-4 p-3 rounded-lg bg-green-100 border border-green-200 text-green-800">
          ✅ {emailStatus}
        </div>
      )}
      
      {reportType === 'hod' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Select Teacher
            </label>
            <select
              value={selectedTeacher}
              onChange={(e) => setSelectedTeacher(e.target.value)}
              className="w-full border rounded px-3 py-2"
            >
              <option value="">Select Teacher</option>
              {Array.from(new Set(subjects?.map(s => s.teacher_name))).filter(Boolean).map(teacher => (
                <option key={teacher} value={teacher}>{teacher}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Select Subject
            </label>
            <select
              value={selectedSubject}
              onChange={(e) => setSelectedSubject(e.target.value)}
              className="w-full border rounded px-3 py-2"
            >
              <option value="">Select Subject</option>
              {subjects?.filter(s => s.teacher_name === selectedTeacher).map(subject => (
                <option key={subject.id} value={subject.name}>{subject.name}</option>
              ))}
            </select>
          </div>
        </div>
      )}
      
      <div className="flex flex-wrap gap-3">
        {reportType === 'hod' && (
          <button
            onClick={sendEmailReport}
            className="bg-red-600 text-white px-4 py-2 rounded hover:bg-red-700 transition"
          >
            Compose Email
          </button>
        )}
        
        <button
          onClick={generateCSV}
          disabled={isGenerating}
          className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700 transition disabled:bg-green-400"
        >
          {isGenerating ? 'Generating...' : 'Export CSV'}
        </button>
        
        <button
          onClick={generatePDF}
          disabled={isGenerating}
          className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition disabled:bg-blue-400"
        >
          {isGenerating ? 'Generating...' : 'Export Full PDF'}
        </button>
        
        <button
          onClick={generateSummaryPDF}
          disabled={isGenerating}
          className="bg-purple-600 text-white px-4 py-2 rounded hover:bg-purple-700 transition disabled:bg-purple-400"
        >
          {isGenerating ? 'Generating...' : 'Export Summary PDF'}
        </button>
      </div>
      
      <div className="mt-4 text-sm text-gray-600">
        <p>• Compose Email: Send custom email to teacher (HOD only)</p>
        <p>• CSV: Raw data for spreadsheet analysis</p>
        <p>• Full PDF: Complete report with all feedback details</p>
        <p>• Summary PDF: Statistical overview and charts</p>
      </div>

      {showEmailComposer && (
        <EmailComposer
          teachers={teachers || []}
          subjects={subjects || []}
          onEmailSent={handleEmailSent}
          onClose={() => setShowEmailComposer(false)}
        />
      )}
    </div>
  );
}
