# Generated by Django 5.2 on 2026-03-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_feedback_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default='TEMP', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
