# Generated by Django 5.2.12 on 2026-03-25 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='offering',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='users.subjectoffering'),
        ),
    ]
