# Generated by Django 5.2.12 on 2026-03-25 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_feedback_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.branch')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.semester')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student-Semester Assignment',
                'verbose_name_plural': 'Student-Semester Assignments',
            },
        ),
    ]
