# Generated by Django 5.2.12 on 2026-04-12 09:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_remove_user_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Question text')),
                ('question_type', models.CharField(choices=[('RATING', 'Rating (1-5)'), ('TEXT', 'Text Feedback'), ('MULTIPLE_CHOICE', 'Multiple Choice')], default='RATING', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('TEACHING', 'Teaching Quality'), ('PUNCTUALITY', 'Punctuality'), ('CLARITY', 'Clarity of Explanation'), ('INTERACTION', 'Student Interaction'), ('BEHAVIOR', 'Teacher Behavior'), ('GENERAL', 'General Feedback')], max_length=20)),
                ('weight', models.FloatField(default=1.0, help_text='Weight for analytics calculation')),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choices', models.JSONField(blank=True, default=dict, help_text='JSON object for multiple choice options')),
            ],
            options={
                'ordering': ['order', 'category', 'text'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.CreateModel(
            name='FeedbackSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'ODD 2024'", max_length=100)),
                ('type', models.CharField(choices=[('ODD', 'Odd Semester'), ('EVEN', 'Even Semester')], max_length=4)),
                ('year', models.IntegerField(help_text='Academic year')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Once locked, no modifications allowed')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-type'],
                'unique_together': {('type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Form name for identification', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='users.feedbacksession')),
            ],
            options={
                'ordering': ['-session__year', 'name'],
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SessionOffering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_students', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_offerings', to='users.subjectoffering')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='users.feedbacksession')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'hod']}, on_delete=django.db.models.deletion.CASCADE, related_name='session_offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session__year', 'base_offering'],
                'unique_together': {('session', 'base_offering')},
            },
        ),
        migrations.CreateModel(
            name='FormQuestionMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0, help_text='Display order in this specific form')),
                ('is_required', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.feedbackform')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_mappings', to='users.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('form', 'question')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.feedbackform')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.feedbacksession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.sessionoffering')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['session', 'student'], name='users_feedb_session_12342f_idx'), models.Index(fields=['offering', 'submitted_at'], name='users_feedb_offerin_e41f6a_idx')],
                'unique_together': {('student', 'offering')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text_response', models.TextField(blank=True)),
                ('multiple_choice_response', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.feedbackform')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.feedbacksession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.question')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.sessionoffering')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['session', 'student'], name='users_feedb_session_6c789d_idx'), models.Index(fields=['offering', 'question'], name='users_feedb_offerin_0d3524_idx'), models.Index(fields=['form', 'submitted_at'], name='users_feedb_form_id_e3ad65_idx')],
                'unique_together': {('student', 'offering', 'question')},
            },
        ),
    ]
