# Generated by Django 5.2.12 on 2026-04-25 15:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_question_alter_user_options_feedbacksession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text_response', models.TextField(blank=True)),
                ('choice_response', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),

        migrations.AlterModelOptions(
            name='feedbackresponse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='feedbacksubmission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentsemester',
            options={},
        ),

        migrations.AddField(
            model_name='feedbackresponse',
            name='overall_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='sentiment_label',
            field=models.CharField(default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'hod']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbacksession',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Once closed, no feedback submissions allowed'),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='anonymous_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='overall_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='sentiment_label',
            field=models.CharField(default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='class_name',
            field=models.CharField(default='A', help_text='Class/Section name', max_length=50),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='users.feedbacksession'),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, help_text='e.g., Lecturer, Senior Lecturer, Professor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.feedbackform'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sessionoffering'),
        ),
        migrations.AlterField(
            model_name='feedbacksubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.feedbackform'),
        ),
        migrations.AlterField(
            model_name='feedbacksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbacksubmission',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='studentsemester',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentsemester',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_semesters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentsemester',
            unique_together={('student', 'session')},
        ),
        migrations.AddIndex(
            model_name='studentsemester',
            index=models.Index(fields=['session', 'branch', 'semester'], name='users_stude_session_e51a28_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsemester',
            index=models.Index(fields=['student', 'is_active'], name='users_stude_student_a78efc_idx'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='response_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.feedbackresponse'),
        ),
        migrations.AddField(
            model_name='submissiontracker',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sessionoffering'),
        ),
        migrations.AddField(
            model_name='submissiontracker',
            name='response_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.feedbackresponse'),
        ),
        migrations.AddField(
            model_name='submissiontracker',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.feedbacksession'),
        ),
        migrations.AddField(
            model_name='submissiontracker',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),

        migrations.RemoveField(
            model_name='feedbackresponse',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='multiple_choice_response',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='text_response',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='user_agent',
        ),
        migrations.AddIndex(
            model_name='submissiontracker',
            index=models.Index(fields=['student', 'session'], name='users_submi_student_1ee408_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissiontracker',
            unique_together={('student', 'offering')},
        ),
    ]
