# Generated by Django 5.2.12 on 2026-04-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_question_alter_user_options_feedbacksession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksession',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Once closed, no feedback submissions allowed'),
        ),
    ]
