# Generated by Django 5.2.12 on 2026-04-12 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_feedbacksession_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(help_text='Unique enrollment number', max_length=20, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studentsemester',
            options={},
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='class_name',
            field=models.CharField(default='A', help_text='Class/Section name', max_length=50),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='users.feedbacksession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsemester',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentsemester',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_semesters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentsemester',
            unique_together={('student', 'session')},
        ),
        migrations.AddIndex(
            model_name='studentsemester',
            index=models.Index(fields=['session', 'branch', 'semester'], name='users_stude_session_e51a28_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsemester',
            index=models.Index(fields=['student', 'is_active'], name='users_stude_student_a78efc_idx'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile_extended', to=settings.AUTH_USER_MODEL),
        ),
    ]
