# Generated by Django 5.2.12 on 2026-03-23 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subject_branch_subject_semester_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='branch',
        ),
        migrations.AddField(
            model_name='subject',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='users.branch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='enrolled_subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
