# Generated by Django 5.2.12 on 2026-04-26 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_answer_submissiontracker_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='offering',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
        migrations.DeleteModel(
            name='FeedbackWindow',
        ),
        migrations.RemoveIndex(
            model_name='feedbackresponse',
            name='users_feedb_session_6c789d_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedbackresponse',
            name='users_feedb_offerin_0d3524_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedbackresponse',
            name='users_feedb_form_id_e3ad65_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedbacksubmission',
            name='users_feedb_session_12342f_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedbacksubmission',
            name='users_feedb_offerin_e41f6a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='feedbackresponse',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sessionoffering',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'hod']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_offerings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
