# Generated by Django 5.2.12 on 2026-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_studentprofile_alter_studentsemester_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, help_text='e.g., Lecturer, Senior Lecturer, Professor', max_length=100, null=True),
        ),
    ]
