# Generated by Django 5.2.12 on 2026-04-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_designation_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksubmission',
            name='overall_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
